=== Haavi97/IAS0060-Robotics-2021/src/ucat_simulator/ucat_simulator-master/uwsim_arrows/data/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?,enablePhysics?,gravity?,physicsWater?,physicsFrequency?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,virtualCamera*, structuredLightProjector*, rangeSensor*, objectPicker*, imu*, pressureSensor*, gpsSensor*, dvlSensor*, virtualRangeImage*,multibeamSensor*, simulatedDevices?, 
echo*
,vehiclePhysics*
,vehicleMass*
,vehicleForce*
,vehicleBuoyance*
,vehicleDrag*
,vehicleThruster*
,flipper*
,directionalReceiver*
,beaconReceiver*
,skeletonFin*
,passiveFin*
,gameCamera?
,game2D?
 )>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?, parameters?, showpath?)>
<!ELEMENT virtualRangeImage (name,relativeTo,resw?,resh?,position?,orientation?,parameters?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT objectPicker (name,relativeTo,range,position?,orientation?)>
<!ELEMENT imu (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT pressureSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT gpsSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT dvlSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT multibeamSensor (name,relativeTo,position?,orientation?, initAngle,finalAngle, angleIncr,range)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,offsetp?,offsetr?,physics?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (WorldToROSTF*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?, (ImuToROSImu*)?, (PressureSensorToROS*)?, (GPSSensorToROS*)?, (DVLSensorToROS*)?, (RangeImageSensorToROSImage*)?,(multibeamSensorToLaserScan*)?
, (SimulatedDeviceROS*)?
, skeletonFinROS*
, gameCameraROS*
, flipperROS?
, depth2SonarROS*
, fluidPressureROS*
, beaconReceiverROS*
, vehicleBuoyanceROS*
, vehicleForceROS*
)>

<!ELEMENT structuredLightProjector (name,relativeTo,fov,image_name,visible?,position?,orientation?)>

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT std (#PCDATA)>


<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>
<!ELEMENT enablePhysics (#PCDATA)>
<!ELEMENT gravity (x,y,z)>
<!ELEMENT physicsWater (size,position,resolution)>
<!ELEMENT size (minX,maxX,minY,maxY,minZ,maxZ)>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT minX (#PCDATA)>
<!ELEMENT maxX (#PCDATA)>
<!ELEMENT minY (#PCDATA)>
<!ELEMENT maxY (#PCDATA)>
<!ELEMENT minZ (#PCDATA)>
<!ELEMENT maxZ (#PCDATA)>
<!ELEMENT physicsFrequency (#PCDATA)>


<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>
<!ELEMENT showpath (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!--elementos structuredLightProjector -->
<!ELEMENT image_name (#PCDATA)>

<!--elementos multibeamSensor -->
<!ELEMENT initAngle (#PCDATA)>
<!ELEMENT finalAngle (#PCDATA)>
<!ELEMENT angleIncr (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName, visualize?)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?, frameId?)>
<!ELEMENT WorldToROSTF  (rootName, enableObjects?, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?,depth?)>
<!ELEMENT RangeImageSensorToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,blackWhite?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>
<!ELEMENT ImuToROSImu (name, topic, rate?)>
<!ELEMENT PressureSensorToROS (name, topic, rate?)>
<!ELEMENT GPSSensorToROS (name, topic, rate?)>
<!ELEMENT DVLSensorToROS (name, topic, rate?)>
<!ELEMENT multibeamSensorToLaserScan (name, topic, rate?)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT blackWhite (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT visualize (#PCDATA)>
<!ELEMENT rootName (#PCDATA)>
<!ELEMENT enableObjects (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!-- elementos physics -->
<!ELEMENT physics (mass?,inertia?,collisionShapeType?,linearDamping?,angularDamping?,isKinematic? , minLinearLimit?, maxLinearLimit?,minAngularLimit?,maxAngularLimit?)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT inertia (x,y,z)>
<!ELEMENT collisionShapeType (#PCDATA)>
<!ELEMENT linearDamping (#PCDATA)>
<!ELEMENT angularDamping (#PCDATA)>
<!ELEMENT minLinearLimit (x,y,z)>
<!ELEMENT maxLinearLimit (x,y,z)>
<!ELEMENT isKinematic (#PCDATA)>
<!ELEMENT minAngularLimit (x,y,z)>
<!ELEMENT maxAngularLimit (x,y,z)>
<!ELEMENT forceType (#PCDATA)>

<!ELEMENT echo (name, info )>
<!ELEMENT echoROS (name, topic, rate?)>

<!-- vehiclePhysics -->
<!ELEMENT vehiclePhysics (name, linkName, physics, debugForceRatio?)>
<!ELEMENT maxForce (#PCDATA)>
<!ELEMENT maxTorque (#PCDATA)>
<!ELEMENT vehicleMass (name, relativeTo, mass+, position*, debugForceRatio?, color?)>
<!ELEMENT vehicleDrag (name, relativeTo, radius, tranDrag, maxForce?, maxTorque?, tranLift?, rotDrag?, position?, isROS?, debugForceRatio?, color?)>
<!ELEMENT vehicleBuoyance (name, relativeTo, radius+, mass+, position*, isROS?, debugForceRatio?, color?)>
<!ELEMENT vehicleThruster (name, relativeTo, radius+, position*, orientation*, defaultForce*, isROS?, debugForceRatio?, color?)>
<!ELEMENT vehicleForce (name, relativeTo, forceType, position, isROS?)>

<!ELEMENT tranDrag (x,y,z)>
<!ELEMENT rotDrag (r,p,y)>
<!ELEMENT tranLift (x,y,z)>
<!ELEMENT defaultForce (x,y,z)>
<!ELEMENT debugForceRatio (#PCDATA)>
<!ELEMENT linkName (#PCDATA)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT isROS (#PCDATA)>

<!ELEMENT vehicleThrusterROS (vehicleName, topic, infoTopic?, rate?)>
<!ELEMENT vehicleBuoyanceROS (vehicleName, topic, infoTopic?, rate?)>
<!ELEMENT vehicleDragROS (vehicleName, topic, infoTopic?, rate?)>
<!ELEMENT vehicleMassROS (vehicleName, topic, infoTopic?, rate?)>

<!ELEMENT angle (#PCDATA)>
<!ELEMENT sensitiveTo (#PCDATA)>
<!ELEMENT numberOfLines (#PCDATA)>
<!ELEMENT directionalReceiver (name, relativeTo, sensitiveTo*, range, angle, numberOfLines?, visible?, position?, orientation?)>
<!ELEMENT directionalReceiverROS (name, topic, rate?)>

<!ELEMENT requiresLineOfSight (#PCDATA)>
<!ELEMENT notBlockedBy (#PCDATA)>
<!ELEMENT measurementStd (#PCDATA)>
<!ELEMENT beaconPosStd (#PCDATA)>
<!ELEMENT beaconReceiver (name, relativeTo, sensitiveTo*, requiresLineOfSight?, notBlockedBy*, range, visible?, position?, orientation?, measurementStd?, beaconPosStd?)>
<!ELEMENT beaconReceiverROS (name, topic, rate?)>

<!ELEMENT skeletonFinROS (vehicleName, topic)>
<!ELEMENT jointName (#PCDATA)>
<!ELEMENT side (#PCDATA)>
<!ELEMENT forceAngle (#PCDATA)>
<!ELEMENT forceMultiplier (#PCDATA)>
<!ELEMENT multPower (#PCDATA)>
<!ELEMENT borderBack (#PCDATA)>
<!ELEMENT skeletonFin (name, relativeTo, side, radius, jointName*, position?, orientation?, debugForceRatio?, color?, forceMultiplier?, maxForce?, multPower?, borderBack?, forceAngle?)>

<!ELEMENT maxSpeed (#PCDATA)>
<!ELEMENT divisor (#PCDATA)>
<!ELEMENT publishAll (#PCDATA)>
<!ELEMENT passiveFin (name, relativeTo, side, radius, jointName*, position?, orientation?, maxSpeed?, divisor?)>

<!ELEMENT distance (#PCDATA)>
<!ELEMENT trackMode (#PCDATA)>
<!ELEMENT gameCamera (name, distance, trackMode, orientation, l*)>

<!ELEMENT type (#PCDATA)>
<!ELEMENT gameCameraROS (name, type, topic)>

<!ELEMENT game2D (name, relativeTo, radius, distance, distanceDivisor, entrance*)>
<!ELEMENT distanceDivisor (#PCDATA)>
<!ELEMENT entrance (x,y,z)>

<!ELEMENT flipperROS (vehicleName, topic)>

<!ELEMENT l (k,en,et?,ru?)>
<!ELEMENT en (#PCDATA)>
<!ELEMENT et (#PCDATA)>
<!ELEMENT ru (#PCDATA)>

<!ELEMENT flipper (name, relativeTo, radius, jointName*, position?, orientation?, debugForceRatio?, color?, forceMultiplier?, maxForce?, multPower?, forceAngle?)>

<!ELEMENT depth2SonarROS (name, topic, frameId, divisor, publishAll?, infoTopic?, rate?)>
<!ELEMENT fluidPressureROS (name, topic, frameId, rate?)>

<!ELEMENT vehicleForceROS (name, topic)>

=== Haavi97/IAS0060-Robotics-2021/src/ucat_simulator/ucat_simulator-master/uwsim_arrows/data/scenes/wreck.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
	<oceanState>
		<windx> 0.04 </windx>
		<windy> 0.04 </windy>
		<windSpeed> 12 </windSpeed>
		<depth> 200 </depth>
		<reflectionDamping> 0.35 </reflectionDamping>
		<waveScale> 0 </waveScale>
		<isNotChoppy> 1 </isNotChoppy>
		<choppyFactor> 0 </choppyFactor>
		<crestFoamHeight> 0 </crestFoamHeight>
		<oceanSurfaceHeight> 0 </oceanSurfaceHeight>
		<fog>
			<density> 0.09</density>
			<color>
				<r>0</r>
				<g>0.05</g>
				<b>0.3</b>
			</color>
		</fog>
		<color>
			<r>0.0</r>
			<g>0.05</g>
			<b>0.3</b>
		</color>
		<attenuation>
			<r>0.015</r>
			<g>0.0075 </g>
			<b> 0.005 </b>
		</attenuation>
	</oceanState>
	<simParams>
		<disableShaders> 0 </disableShaders>
		<resw> 1024 </resw>
		<resh> 768 </resh>
		<offsetp>
			<x>0</x>
			<y>0</y>
			<z>0</z>
		</offsetp>
		<offsetr>
			<x>0</x>
			<y>0</y>
			<z>0</z>
		</offsetr>
		<enablePhysics> 1 </enablePhysics>
		<gravity>
			<x> 0</x>
			<y> 0</y>
			<z> -9.81 </z>
		</gravity>
		<physicsFrequency>200</physicsFrequency>
	</simParams>
	<camera>
		<freeMotion> 0 </freeMotion>
		<objectToTrack>ucat0/base_link</objectToTrack>
		<fov> 78 </fov>
		<aspectRatio> 1.33 </aspectRatio>
		<near> 0.01 </near>
		<far> 10000 </far>
		<position>
			<x> 0 </x>
			<y> 2 </y>
			<z> -1.5 </z>
		</position>
		<lookAt>
			<x> 2 </x>
			<y> 2 </y>
			<z> -1.5 </z>
		</lookAt>
	</camera>

	<vehicle>
		<name>ucat0</name>
		<file>robots/U-CAT.urdf</file>
		<!--U-CAT Position -->
		<position>
			<x> 8 </x>
			<y> 8 </y>
			<z> -10 </z>
		</position>
		<orientation>
			<r>0</r>
			<p>0</p>
			<y>1.55</y>
		</orientation>
		
		<virtualCamera>
			<name>ucat0_camera</name>
			<relativeTo>camera_link</relativeTo>
			<resw> 640 </resw>
			<resh> 480 </resh>
			 
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			
			<frameId> camera_link_optical </frameId>
		</virtualCamera>

		<!-- <structuredLightProjector> <name>laser_projector</name> <relativeTo>base_link</relativeTo> 
			<fov>30</fov> <image_name>meshes/flashlamp256.png</image_name> <visible>1</visible> 
			<position> <x>0.3</x> <y> 0 </y> <z>-0.1</z> </position> <orientation> <r>1.07</r> 
			<p>0</p> <y>-1.57</y> </orientation> </structuredLightProjector> -->	
		
		<imu>
			<name>imu</name>
			<relativeTo>base_link</relativeTo>
			<position>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</position>
			<orientation>
				<r>0</r>
				<p>0</p>
				<y>0</y>
			</orientation>
			<std>0.00000001</std>
		</imu>

		<pressureSensor>
			<name>pressureSensor</name>
			<relativeTo>base_link</relativeTo>
			<position>
				<x>0</x>
				<y>0</y>
				<z>0.13</z>
			</position>
			<orientation>
				<r>0</r>
				<p>0</p>
				<y>0</y>
			</orientation>
			<std>0.02</std>
		</pressureSensor>

		<virtualRangeImage>
			<name>ucat0_sonar_ff</name>
			<relativeTo>sonar_ff</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>40</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>
		
		<virtualRangeImage>
			<name>ucat0_sonar_fl</name>
			<relativeTo>sonar_fl</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>40</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>
		
		<virtualRangeImage>
			<name>ucat0_sonar_fr</name>
			<relativeTo>sonar_fr</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>40</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<virtualRangeImage>
			<name>ucat0_sonar_fu</name>
			<relativeTo>sonar_fu</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>40</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<virtualRangeImage>
			<name>ucat0_sonar_fd</name>
			<relativeTo>sonar_fd</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>40</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<virtualRangeImage>
			<name>ucat0_sonar_l</name>
			<relativeTo>sonar_l</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>20</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<virtualRangeImage>
			<name>ucat0_sonar_r</name>
			<relativeTo>sonar_r</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>20</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<virtualRangeImage>
			<name>ucat0_sonar_b</name>
			<relativeTo>sonar_b</relativeTo>
			<resw> 64 </resw>
			<resh> 64 </resh>
			<orientation>
				<r>1.57</r>
				<p>0</p>
				<y>-1.57</y>
			</orientation>
			<parameters>
				<fx>110</fx>
				<fy>110</fy>
				<x0>32</x0>
				<y0>32</y0>
				<f>20</f>
				<n>0.03</n>
				<k>0</k>
			</parameters>
		</virtualRangeImage>

		<vehiclePhysics>
			<name>arrows_physics</name>
			<linkName>base_link</linkName>
			<physics>
				<mass> 20 </mass>
				<inertia>
					<x> 0.144 </x>
					<y> 0.275306667 </y>
					<z> 0.275306667 </z>
				</inertia>
				<collisionShapeType>compound box</collisionShapeType>
				<linearDamping>0.1</linearDamping>
				<angularDamping>0.1</angularDamping>
				<isKinematic>0</isKinematic>
			</physics>
			<debugForceRatio>0</debugForceRatio>
		</vehiclePhysics>

		<vehicleMass>
			<name>main_mass</name>
			<relativeTo>base_link</relativeTo>
			<mass>10</mass>
			<mass>10</mass>
			<position>
				<x> 0.10 </x>
				<y> 0.0 </y>
				<z> -0.04 </z>
			</position>
			<position>
				<x> -0.10 </x>
				<y> 0.0 </y>
				<z> -0.04 </z>
			</position>
			<debugForceRatio>0.0005</debugForceRatio>
			<color>
				<r> 0 </r>
				<g> 0 </g>
				<b> 0 </b>
			</color>
		</vehicleMass>
		
		<vehicleForce>
			<name>center_of_mass</name>
			<relativeTo>base_link</relativeTo>
			<forceType>G</forceType>
			<position>
				<x> 0.0 </x>
				<y> 0.0 </y>
				<z> -0.04 </z>
			</position>
			<isROS>1</isROS>
		</vehicleForce>
		
		<vehicleBuoyance>
			<name>buoyance</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.05</radius>
			<mass>0</mass>
			<mass>0</mass>
			<position>
				<x> 0.13 </x>
				<y> 0 </y>
				<z> 0.05 </z>
			</position>
			<position>
				<x> -0.13 </x>
				<y> 0 </y>
				<z> 0.05 </z>
			</position>
			<isROS>1</isROS>
			<debugForceRatio>1</debugForceRatio>
			<color>
				<r> 1 </r>
				<g> 1 </g>
				<b> 1 </b>
			</color>
		</vehicleBuoyance>

		<vehicleBuoyance>
			<name>floater</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.15</radius>
		<!-- 			<mass>-10.5</mass> -->
		<!-- 			<mass>-9.5</mass> -->
			<mass>-10</mass>
			<mass>-10</mass>
			<position>
				<x> 0.15 </x>
				<y> 0 </y>
				<z> 0 </z>
			</position>
			<position>
				<x> -0.15 </x>
				<y> 0 </y>
				<z> 0 </z>
			</position>
			<debugForceRatio>0.001</debugForceRatio>
			<color>
				<r> 0 </r>
				<g> 0 </g>
				<b> 1 </b>
			</color>
		</vehicleBuoyance>

		<vehicleDrag>
			<name>drag_bodyB</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.14</radius>
			<tranDrag>
				<x> 0.0067824 </x><!-- 0.3 * (3.14 * 0.12^2) / 2 -->
				<y> 0.0576 </y><!-- 0.8 * (0.24 * 0.30) -->
				<z> 0.0576 </z><!-- 0.8 * (0.24 * 0.30) -->
			</tranDrag>
			<maxForce>10000</maxForce>
			<tranLift>
				<x> 0 </x>
				<y> 0 </y>
				<z> 0 </z>
			</tranLift>
			<position>
				<x> -0.20 </x>
				<y> 0.0 </y>
				<z> 0.0 </z>
			</position>
			<debugForceRatio>0.1</debugForceRatio>
			<color>
				<r> 0 </r>
				<g> 1 </g>
				<b> 0 </b>
			</color>
		</vehicleDrag>

		<vehicleDrag>
			<name>drag_bodyF</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.14</radius>
			<tranDrag>
				<x> 0.0067824 </x><!-- 0.3 * (3.14 * 0.12^2) / 2 -->
				<y> 0.0576 </y><!-- 0.8 * (0.24 * 0.30) -->
				<z> 0.0576 </z><!-- 0.8 * (0.24 * 0.30) -->
			</tranDrag>
			<maxForce>10000</maxForce>
			<tranLift>
				<x> 0 </x>
				<y> 0 </y>
				<z> 0 </z>
			</tranLift>
			<position>
				<x> 0.20 </x>
				<y> 0.0 </y>
				<z> 0.0 </z>
			</position>
			<debugForceRatio>0.1</debugForceRatio>
			<color>
				<r> 0 </r>
				<g> 1 </g>
				<b> 0 </b>
			</color>
		</vehicleDrag>

		<vehicleDrag>
			<name>drag_bodyL</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.04</radius>
			<tranDrag>
				<x> 0.0 </x>
				<y> 0.0 </y>
				<z> 0.021 </z> <!-- 0.3*0.07*1 -->
			</tranDrag>
			<maxForce>500</maxForce>
			<tranLift>
				<x> 0 </x>
				<y> 0 </y>
				<z> 0 </z>
			</tranLift>
			<position>
				<x> 0.00 </x>
				<y> 0.15 </y>
				<z> 0.0 </z>
			</position>
			<debugForceRatio>1</debugForceRatio>
			<color>
				<r> 0 </r>
				<g> 1 </g>
				<b> 0 </b>
			</color>
		</vehicleDrag>

		<vehicleDrag>
			<name>drag_bodyR</name>
			<relativeTo>base_link</relativeTo>
			<radius>0.04</radius>
			<tranDrag>
				<x> 0.000 </x>
				<y> 0.000 </y>
				<z> 0.021 </z>
			</tranDrag>
			<maxForce>500</maxForce>
			<tranLift>
				<x> 0 </x>
				<y> 0 </y>
				<z> 0 </z>
			</tranLift>
			<position>
				<x> 0.00 </x>
				<y> -0.15 </y>
